// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29/01/2026 16:31:55
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/quentincontreau/developpement/ProjetFileRouge - Front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/plugins/**/*.{js,ts,mjs}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/composables/**/*.{js,ts,mjs}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/utils/**/*.{js,ts,mjs}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/quentincontreau/developpement/ProjetFileRouge - Front/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;